### ISSUE TITLE
The readme example doesn't correspond to the actual behavior

### ISSUE THREAD

**Issue by pavelgit** [ikr/normalize-for-search#11]
Hi,
the readme states: 
```
normalizeForSearch('Dät ist naïve und ÜBERCOOL, ё-маё!');
// 'dat ist naive und ubercool, е-мае!'
```

But the normalize.test.js file says a bit different thing:
```
assert.strictEqual(
	normalizeForSearch('Dät ist naïve und ÜBERCOOL, ё-маё!'),
	'daet ist naive und uebercool, е-мае!'
);
```

I mean, the function maps "ä" -> "ae", not "a". The same with other umlauts.

Thank you!

**Comment by ikr** [comment]
Indeed. Corrected with fee6029d5373c7f15f6043a46975f5f7ed7100ae. Thanks!
