### ISSUE TITLE
Fails, when given a number

### ISSUE THREAD

**Issue by euleule** [ikr/normalize-for-search#9]
When using the normalizeForSearch() function I would like it to be fault tolerant when given numbers, so I can use it without thinking about the parameters I pass to it.

**Current**
When passed an int the function crashes.

**Desired**
When passed an int the function returns the String representation of the int.

**Comment by derhuerst** [comment]
Why don't just do `normalize('' + value)`?

**Comment by ikr** [comment]
I'm not in favor of overly flexible function arguments. They cause certain bugs propagate much further before they get noticed. I'll put a note in the README on `normalizeForSearch` expecting strictly a `String` as an input.
